repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: cargo +nightly fmt
        language: system
        types: [rust]
        pass_filenames: false

      - id: clippy-fix
        name: clippy (fix)
        entry: cargo clippy --all-targets --fix --allow-dirty --allow-staged -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: clippy
        name: clippy
        entry: cargo clippy --all-targets -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: cargo test -- --test-threads=1
        language: system
        types: [rust]
        pass_filenames: false
