repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
        args: [--all-targets, --fix, --allow-dirty, --allow-staged, --, -D, warnings]
      - id: clippy
        args: [--all-targets, --, -D, warnings]

  - repo: local
    hooks:
      - id: cargo-test
        name: cargo test
        entry: cargo test -- --test-threads=1
        language: system
        types: [rust]
        pass_filenames: false
